### ISSUE TITLE
Java VM crashes using mutliple instances on 64-bit environment

### ISSUE THREAD

**Issue by patsimm** [traff/pty4j#29]
Hello,

I don't know if this is the fault of pty4j or the underlying winpty or even my own. So I have a java application that opens multiple terminals using JediTerm. When I open the second Terminal on a 64-bit Java environment I get the following error:

    #
    # A fatal error has been detected by the Java Runtime Environment:
    #
    #  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00000000776e32d0, pid=2076, tid=4092
    #
    # JRE version: 7.0_13-b20
    # Java VM: Java HotSpot(TM) 64-Bit Server VM (23.7-b01 mixed mode windows-amd64 compressed oops)
    # Problematic frame:
    # C  [ntdll.dll+0x532d0]  RtlFreeHeap+0xd0
    #
    # Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
    #
    # An error report file with more information is saved as:
    # C:\Users\...\hs_err_pid2076.log
    #
    # If you would like to submit a bug report, please visit:
    #   http://bugreport.sun.com/bugreport/crash.jsp
    # The crash happened outside the Java Virtual Machine in native code.
    # See problematic frame for where to report the bug.
    #

This happens on every 64-bit java version as far as I have seen. When I use a 32-bit java version every thing works as expected.

I also got the following exception thrown:

    Exception in thread "AWT-EventQueue-0" java.lang.Error: Invalid memory access
            at com.sun.jna.Native.invokeInt(Native Method)
            at com.sun.jna.Function.invoke(Function.java:383)
            at com.sun.jna.Function.invoke(Function.java:315)
            at com.sun.jna.Library$Handler.invoke(Library.java:212)
            at com.pty4j.windows.$Proxy1.winpty_start_process(Unknown Source)
            at com.pty4j.windows.WinPty.<init>(WinPty.java:45)
            at com.pty4j.windows.WinPtyProcess.<init>(WinPtyProcess.java:37)
            at com.pty4j.PtyProcess.exec(PtyProcess.java:77)
            at com.pty4j.PtyProcess.exec(PtyProcess.java:50)

Edit: I tested this behaviour now by just starting the class PtyMain from jediterm which reproduces the issue.

**Comment by patsimm** [comment]
Ok, rebuilding winpty solved the issue.
